/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js in normal projects.
// We're creating it manually since we’re wiring things up by hand.
